# Generated by Django 3.2 on 2022-12-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_number',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
