# Generated by Django 3.2 on 2022-12-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(db_index=True, default='626859862', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='tax_number',
            field=models.CharField(db_index=True, default='641914', max_length=7),
        ),
    ]
